class QueryParser:
    def parse(self, query):
        if "what" in query or "introduce" in query:
            return "informational"
        elif "calculate" in query or "summarize" in query:
            return "tool_call"
        else:
            return "default"


class RAGRetriever:
    def retrieve(self, query):
        # 模拟检索相似文段（真实项目用向量搜索）
        return ["This is information 1...", "This is information 2..."]


class PromptAssembler:
    def assemble(self, query, context_chunks):
        context = "\n".join(context_chunks)
        return f"""Please answer the questions based on the following knowledge:
[knowledge: content]
{context}
[Question:]
{query}
[Answer]
"""


class LLMResponder:
    def generate(self, prompt):
        # 模拟调用 Claude、GPT 等模型
        return "This is the answer generated by the model based on the context."


class AgentPlanner:
    def __init__(self):
        self.parser = QueryParser()
        self.retriever = RAGRetriever()
        self.assembler = PromptAssembler()
        self.llm = LLMResponder()

    def run(self, query):
        intent = self.parser.parse(query)

        if intent == "informational":
            chunks = self.retriever.retrieve(query)
            prompt = self.assembler.assemble(query, chunks)
        else:
            prompt = f"{query}\nPlease answer directly。"

        answer = self.llm.generate(prompt)
        return answer


# === 使用示例 ===
agent = AgentPlanner()
user_query = "What is a vector database?"
response = agent.run(user_query)
print(response)
